const SUPABASE_URL="https://duaqxvfgwkaigbycgzjg.supabase.co";
const SUPABASE_KEY="sb_publishable_s9VcXCZ3yTnb6x9cXRzpzA_afd1YPWc";
const PIN="2202",BUCKET="memories";
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=id=>document.getElementById(id);
const anniversary=new Date("2026-08-22T00:00:00+02:00"),met=new Date("2026-01-23T00:00:00+02:00"),dating=new Date("2026-02-22T00:00:00+02:00");
function updateCountdown(){let d=anniversary-new Date();if(d<=0){["days","hours","minutes","seconds"].forEach(x=>$(x).textContent="00");$("surpriseBtn").disabled=false;$("surpriseBtn").textContent="Open Your Surprise 🎁";$("surpriseTitle").textContent="Happy Six Months ❤️";$("surpriseText").textContent="The final chapter is ready for you.";document.querySelector(".lock").textContent="❤️";return}let v=[Math.floor(d/86400000),Math.floor(d/3600000)%24,Math.floor(d/60000)%60,Math.floor(d/1000)%60];["days","hours","minutes","seconds"].forEach((x,i)=>$(x).textContent=String(v[i]).padStart(2,"0"))}
function wholeDays(d){let n=new Date(),a=Date.UTC(n.getFullYear(),n.getMonth(),n.getDate()),b=Date.UTC(d.getFullYear(),d.getMonth(),d.getDate());return Math.max(0,Math.floor((a-b)/86400000))}
function counters(){$("daysKnown").textContent=wholeDays(met);$("daysDating").textContent=wholeDays(dating)}
updateCountdown();counters();setInterval(updateCountdown,1000);setInterval(counters,60000);
let h=new Date().getHours();$("greeting").textContent=h<5?"You should probably be sleeping… but I’m glad you’re here ❤️":h<12?"Good morning, beautiful ☀️":h<18?"Good afternoon, gorgeous ❤️":h<23?"Good evening, my love 🌙":"You should probably be sleeping… but I’m glad you’re here ❤️";
const reasons=["I love the way you make ordinary days feel special.","I love the way you look at me.","I love how deeply you care.","I love how loved you make me feel.","I love the way your smile changes the whole mood of a room.","I love how much fun we can have doing absolutely nothing.","I love how safe and appreciated I feel with you.","I love your laugh, especially when I caused it.","I love that I can be completely myself around you.","I love that you are not only my love, but also my favourite person."];let ri=0;$("reasonBtn").onclick=()=>{ri=(ri+1)%reasons.length;$("reasonText").textContent=reasons[ri];$("reasonCount").textContent=`Reason ${ri+1}`};
const letterTexts={1:`<p class="eyebrow">LETTER ONE</p><h2>My Beautiful Angel,</h2><p>I love you so, so, so much, and I wanted to find a unique and fun way to show you that. I was thinking about all the things I could do to remind you how much I love you. I always want to try to give you something different, something thoughtful, or something that makes you smile, and I thought this little website might be a really fun idea.</p><p>You have been so special to me over the past few months. I love the way you treat me, the way you look at me, and the way you love me so deeply. You make me feel so full, so appreciated, and so incredibly loved.</p><p>Every week, I want you to be able to open this website and find another reason to smile. I plan on updating it often with new messages, little surprises, and fun things for you to discover. I hope you enjoy this countdown to our six-month anniversary.</p><p>I know it is not your birthday, but I still wanted to create something that reminds you every day just how special you are to me. 😂</p><p class="signature">Your Love,<br>Rui ❤️</p>`};
function openModal(m){m.classList.add("open");document.body.style.overflow="hidden"}function closeModal(m){m.classList.remove("open");if(!document.querySelector(".modal.open"))document.body.style.overflow=""}
document.querySelectorAll(".letter-card").forEach(c=>{if(new Date()>=new Date(c.dataset.unlock)){c.classList.remove("locked");c.classList.add("unlocked");c.querySelector(".status").textContent="OPEN";c.querySelector(".icon").textContent=c.dataset.letter==="6"?"🎁":"💌";c.querySelector("button").textContent="Read This Letter"}c.querySelector("button").onclick=()=>{if(c.classList.contains("locked"))return toast("This letter is still waiting for its date ❤️");let n=c.dataset.letter;$("letterContent").innerHTML=letterTexts[n]||`<p class="eyebrow">LETTER ${n}</p><h2>This letter is waiting to be written ❤️</h2><p>Add your personal message for this week before its unlock date.</p>`;openModal($("letterModal"))}});
$("closeLetter").onclick=()=>closeModal($("letterModal"));document.querySelector("#letterModal .backdrop").onclick=()=>closeModal($("letterModal"));
$("menuBtn").onclick=()=>$("navLinks").classList.toggle("open");document.querySelectorAll("#navLinks a").forEach(a=>a.onclick=()=>$("navLinks").classList.remove("open"));
const obs=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("visible")),{threshold:.12});document.querySelectorAll(".reveal").forEach(x=>obs.observe(x));
function toast(t){$("toast").textContent=t;$("toast").classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>$("toast").classList.remove("show"),3000)}
document.querySelectorAll(".secret").forEach(x=>x.onclick=()=>toast("Achievement unlocked: you found a secret ❤️"));
let unlocked=sessionStorage.getItem("editMemories")==="yes",pending=null;
function updateControls(){document.querySelectorAll(".memory-controls").forEach(x=>x.hidden=!unlocked);$("unlockBtn").hidden=unlocked;$("lockBtn").hidden=!unlocked}updateControls();
$("unlockBtn").onclick=()=>openModal($("pinModal"));$("closePin").onclick=()=>closeModal($("pinModal"));document.querySelector("#pinModal .backdrop").onclick=()=>closeModal($("pinModal"));$("pinForm").onsubmit=e=>{e.preventDefault();if($("pinInput").value!==PIN)return toast("That PIN is not correct.");unlocked=true;sessionStorage.setItem("editMemories","yes");updateControls();closeModal($("pinModal"));toast("Memory editing unlocked ❤️")};$("lockBtn").onclick=()=>{unlocked=false;sessionStorage.removeItem("editMemories");updateControls();toast("Memory editing locked.")};
function clearCard(c){let i=c.querySelector(".memory-img"),p=c.querySelector(".placeholder");i.hidden=true;i.removeAttribute("src");p.hidden=false;c.querySelector(".loading").hidden=true}
function showCard(c,url,caption){let i=c.querySelector(".memory-img"),p=c.querySelector(".placeholder");i.onload=()=>{i.hidden=false;p.hidden=true;c.querySelector(".loading").hidden=true};i.onerror=()=>clearCard(c);i.src=url+"?v="+Date.now();c.querySelector(".memory-caption").textContent=caption||"A beautiful memory ❤️"}
async function loadMemories(){let {data,error}=await db.from("memories").select("slot,caption,image_path");if(error){console.error(error);return}data.forEach(m=>{let c=document.querySelector(`[data-slot="${m.slot}"]`);if(!c)return;let {data:u}=db.storage.from(BUCKET).getPublicUrl(m.image_path);showCard(c,u.publicUrl,m.caption)})}
document.querySelectorAll(".memory-slot").forEach(c=>{let input=c.querySelector(".file-input"),upload=c.querySelector(".upload"),del=c.querySelector(".delete"),photo=c.querySelector(".photo-button");upload.onclick=()=>unlocked?input.click():toast("Unlock memory editing first.");photo.onclick=()=>{let i=c.querySelector(".memory-img");if(!i.hidden&&i.src){$("largePhoto").src=i.src;$("largeCaption").textContent=c.querySelector(".memory-caption").textContent;openModal($("photoModal"))}else if(unlocked)input.click();else toast("Unlock memory editing to add a picture.")};input.onchange=()=>{let f=input.files?.[0];input.value="";if(!f)return;pending={card:c,file:f,slot:c.dataset.slot};$("captionInput").value="";openModal($("captionModal"))};del.onclick=async()=>{if(!unlocked||!confirm("Delete this memory?"))return;let slot=c.dataset.slot,path=`${slot}.jpg`;await db.storage.from(BUCKET).remove([path]);await db.from("memories").delete().eq("slot",slot);clearCard(c);toast("Memory deleted.")}});
$("closeCaption").onclick=()=>{pending=null;closeModal($("captionModal"))};document.querySelector("#captionModal .backdrop").onclick=$("closeCaption").onclick;$("captionForm").onsubmit=async e=>{e.preventDefault();if(!pending)return;let {card,file,slot}=pending,caption=$("captionInput").value.trim()||"A beautiful memory ❤️";closeModal($("captionModal"));card.querySelector(".loading").hidden=false;try{let blob=await compress(file),path=`${slot}.jpg`;let up=await db.storage.from(BUCKET).upload(path,blob,{contentType:"image/jpeg",upsert:true,cacheControl:"60"});if(up.error)throw up.error;let row=await db.from("memories").upsert({slot,caption,image_path:path,updated_at:new Date().toISOString()},{onConflict:"slot"});if(row.error)throw row.error;let {data:u}=db.storage.from(BUCKET).getPublicUrl(path);showCard(card,u.publicUrl,caption);toast("Memory saved permanently ❤️")}catch(err){console.error(err);card.querySelector(".loading").hidden=true;toast("Upload failed. Check Supabase permissions.")}pending=null};
function compress(file){return new Promise((res,rej)=>{let r=new FileReader();r.onload=()=>{let i=new Image();i.onload=()=>{let s=Math.min(1,1600/Math.max(i.width,i.height)),c=document.createElement("canvas");c.width=i.width*s;c.height=i.height*s;c.getContext("2d").drawImage(i,0,0,c.width,c.height);c.toBlob(b=>b?res(b):rej(new Error("Compression failed")),"image/jpeg",.84)};i.onerror=rej;i.src=r.result};r.onerror=rej;r.readAsDataURL(file)})}
$("closePhoto").onclick=()=>closeModal($("photoModal"));document.querySelector("#photoModal .backdrop").onclick=$("closePhoto").onclick;loadMemories();
